#!/bin/bash
printf '\e[?7l'

shopt -s lastpipe # For syntax
shopt -s extglob # Ensure advanced pattern matching is available
shopt -s checkwinsize; (:) # Enable and then trigger a terminal size refresh
trap redraw WINCH ALRM # Attach WINCH and ALRM to redraw the screen
trap die EXIT HUP USR1 # Attach most exit codes to cleanup and exit
trap quit INT
trap quit SIGTERM

declare -A syntax menuline menufile menuhelp menukey menudebug style about winhelp windowkey editkey wininfo stroke options dialogquit dialogquitmenu
declare -a buffer buffersyntax hexkey optdc
declare -i line base rl offsetst offseten
declare -n menucon window
declare file message modified filetype comment stringone stringtwo reservedlines recmd rst

printf "\e[?1049h" #switch to alternative buffer

version="Spis dev"
buffer=() # File contents
buffersyntax=() # File contents
line=0 # Currently selected line (0 means the buffer is empty)
base=1 # Top-most line shown
rl=0 # how left or right the cursor is
file= # Currently addressed file
message="${version}: insanity" # Feedback text in the status bar
modified=false # Tracking whether a file was modified
reservedlines=2 # Number of lines not displaying file

## config options

options=(
	[mouse]=true
	[todonote]=true
	[defx]=$(( COLUMNS / 2 ))
	[defy]=$(( LINES /2 ))
	[timeout]=0.01
	[tabchar]="."
	[tabchar_alt]=" "
	[refresh_timeout]=1
	[file_prompt]="Path: "
	[button_margin]=2
	[button_padding]=4
)
editkey=(
	[up]=$'\E[A'	[down]=$'\E[B'	[right]=$'\E[C'
	[left]=$'\E[D'	[pgup]=$'\E[5~'	[pgdown]=$'\E[5~'
)
stroke=(
	[18 0]='quit'
	[7 0]='menuhelp'
	[10 0]='up'
	[e 0]='down'
	[6 0]='right'
	[2 0]='left'
	[19 0]='page_down'
	[16 0]='page_up'
	[0]='new_line'
	[c 0]='new_line'
	[f 0]='write_buffer'
	[12 0]='read_buffer'
	[1b 72 0]='set_buffer_file'
	[14 0]='execute'
	[4 0]='delete_line'
	[13 0]='shell'
	[5 0]='mtoggle'
	[7f 0]='backspace'
)
style=(
	[TODO]='\e[3;45m'
	[NOTE]='\e[3;47m'
	[menuline]='\e[0;37;40m'
	[windowline]='\e[0;97;100m'
	[menuitem]='\e[0;37;40m'
	[windowcontent]='\e[97;40m'
	[selected]='\e[30;41m'
	[button]='\e[0;97;100m'
	[interactive]='\e[95;40m'
	[menuitemselected]='\e[30;41m'
	[infoline]='\e[40;97m'
	[number]='\e[0;37m'
	[numberempty]='\e[0;90m'
	[numberselected]='\e[0;91m'
	#syntax
	[quotevar]='\e[0;36;48m'
	[comment]='\e[3;37;48m'
	[variable]='\e[0;96;108m'
	[option]='\e[0;93;108m'
	[flow]='\e[0;93;108m'
	[bracket]='\e[1;95;108m'
	[quote]='\e[0;92;108m'
	[dquote]='\e[0;32;48m'
	[set]='\e[0;94;108m'
	[fn]='\e[0;30;44m'
	[keyword]='\e[0;91;108m'
)
windowkey=(
	[up]=$'\E[A'	[down]=$'\E[B'	[right]=$'\E[C'	[left]=$'\E[D'
	[hsizep]='*'	[hsizem]='/'	[vsizep]='+'	[vsizem]='-'
)
menuline=(
	[File]=menufile	[Help]=menuhelp
	[Keys]=menukey	[Redraw]=refresh
	[Debug]=menudebug
)

menufile() { unset menucon; declare -n menucon=menufile; menu; }
menufile=(
	[Close    C-x ]="quit"
	[Open loc M-r ]="set_buffer_file"
	[Execute  C-t ]="execute"
	[Save     C-o ]="write_buffer"
	[File picker  ]="filepick"
	[Info         ]="wininfo"
)

menuhelp() { unset menucon; declare -n menucon=menuhelp; menu; }
menuhelp=(
	[Keybinding          ]=menukey
	[About float windows ]=winhelpf
	[About               ]=about
)

menukey() { unset menucon; declare -n menucon=menukey; menu; }
menukey=(
	[Exit         C-x ]="quit"
	[New Line C-l | ⏎ ]="new_line"
	[Set target   M-r ]="set_buffer_file"
	[Read File    C-r ]="read_buffer"
	[Write Out    C-o ]="write_buffer"
	[Delete Line  C-d ]="delete_line"
	[Toggle Mouse C-e ]="mtoggle"
	[Prev Line    C-p ]="up"
	[Next Line    C-n ]="down"
	[Prev Page    C-y ]="page_up"
	[Next Page    C-v ]="page_down"
	[Execute      C-t ]="execute"
	[Shell        C-s ]="shell"
)

menudebug() { unset menucon; declare -n menucon=menudebug; menu; }
menudebug=(
	[clear      ]=clr
	[refresh    ]=refresh
	[screen init]=scrinit
	[pickdraw **]=pickdraw
	[die      **]=die
	[main     **]=main
	[backspace  ]=backspace
	[right      ]=right
	[left       ]=left
	[dialogquit ]=dialogquit
)

syntax=(
	[bash]=builtin_syntax_bash	[sh]=builtin_syntax_bash
	[ksh]=builtin_syntax_bash	[mksh]=builtin_syntax_bash
	[dash]=builtin_syntax_bash	[zsh]=builtin_syntax_bash
	[conf]=builtin_syntax_conf	[unknown]=builtin_syntax_unknown
)

about() { unset window; declare -n window=about; float; }
about=(
	[sizex]="${options[defx]}"	[sizey]="${options[defy]}"
	[title]=" About ${version} "
	[content]="${version}, text editor (insanity) in bash. repo: https://github.com/nyeta/spis; based on https://github.com/comfies/bed"
)

winhelpf() { unset window; declare -n window=winhelp; float; }
winhelp=(
	[sizex]="${options[defx]}"	[sizey]="${options[defy]}"
	[title]=" Floating window help "
	[content]="Use tab key to switch focus. When focused on window itself use arrow keys to move the window and / to decrease its width, * to increase, + to increase its height and - to decrease. When focused on choose menu, use left and right arrow to select."
)

wininfo() { unset window; declare -n window=wininfo; wininfo[content]="name: $file; type: $filetype"; float; }
wininfo=(
   	[sizex]="${options[defx]}"	[sizey]="${options[defy]}"
	[title]=" File info "
	#content is set in fucntion, so it can dynamicaly update
)

dialogquit() { unset window; declare -n window=dialogquit; float; }
dialogquit=(
	[sizex]=46 [sizey]=8
	[title]="Unsaved work"
	[content]="Buffer modified, save before close?"
	[type]="choose"
	[options]="dialogquitmenu"
	[layout]="center"
	[default]="save"
	[focus]="choose"
)
dialogquitmenu=(
	[save]="write_buffer; die"
	[quit]="die"
	[cancel]="redraw; return 69"
)

## rest of this garbageware

rst='\e[0;0m'
clr() {
	printf "\033c" # clear
}
refresh() {
	clr
	message="reloaded..."
	hasrefresh=true
	megaredraw
	redraw
	scrinit
	hasrefresh=false
	message=
}
scrinit() {
	printf '\e[?1047h' # Switch to alternative buffer
    [ "${options[mouse]}" = true ] && echo -ne "\e[?1000;1006;1015h" #enable mouse tracking
}

float() {
	local -i dci=0
	change=true
	floatsizex="${window[sizex]}"
	floatsizey="${window[sizey]}"
	floatpositionx=$(( ( COLUMNS / 2 ) - ( floatsizex / 2 )  ))
	floatpositiony=$(( ( LINES / 2 ) - ( floatsizey / 2 ) ))
	if [ -z "${window[focus]}" ]; then
		focus=window
	else
		focus="${window[focus]}"
	fi
	case "${window[type]}" in
		'choose')
			unset chooseopt
			declare -n chooseopt="${window[options]}"
			declare -n layout="${window[layout]}"
			selopt="${window[default]}"
			for is in "${!chooseopt[@]}"; do
				optdc[dci]="$is"
				if [ "$is" = "${selopt}" ]; then
					   seloptdc=$dci
				   fi
				((dci++))
			done
			;;
	esac
	floatwin
}
floatwin() {
	while true; do
		[ "$change" = true ] && {
			redraw
			printf '\e[%s;%sH' $floatpositiony $floatpositionx
			printf "${style[windowline]}%*s\r" $floatsizex
			printf '\e[%s;%sH' $floatpositiony $floatpositionx
			printf '%s\e[m' "${window[title]}"
			local -i rsizey=$(( floatsizey - 1 ))
			local -i csizex=0
			for ((i=1;i<=rsizey;i++)); do
				printf "\e[%s;%sH${style[windowcontent]}%*s\r" $(( floatpositiony + i )) $floatpositionx "$floatsizex"
				printf '\e[%s;%sH%s\n' $(( floatpositiony + i )) $floatpositionx "${window[content]:csizex:floatsizex}"
				csizex=$(( csizex + floatsizex ))
			done
			#draw selection menu
			case "${window[type]}" in
				'choose')
					floatchoose;;
			esac
		}
		winkey
		[ $? = 69 ] && return
	done
}
floatchoose() {
	local -i bm=${options[button_margin]}
	local -i bp=${options[button_padding]}
	local all="${!chooseopt[*]}"
	case "${window[layout]}" in
		right)
			local -i stx=$((floatpositionx + floatsizex - ${#all} - ${#chooseopt[*]} * 2 * bp - ${#chooseopt[*]} * ( bm - 1 ) - 1));;
		left)
			local -i stx=$((floatpositionx + bm));;
		center)
			local -i stx=$((floatpositionx + (floatsizex / 2) - ( (${#all} + ${#chooseopt[*]} * 2 * bp + ${#chooseopt[*]} * (bm - 1) ) / 2 ) ));;
	esac
	local -i sty=$((floatpositiony + floatsizey - 2))
	floatchbpbm
	((sty--))
	(
		for opt in ${!chooseopt[@]}; do
			printf '\e[%s;%sH' $sty $stx
			if [ "$opt" = "$selopt" ]; then
				printf "${style[selected]}%*s${opt}%*s" $bp ' ' $bp ' '
			else
				printf "${style[button]}%*s${opt}%*s" $bp ' ' $bp ' '
			fi
		    stx=$((stx + ${#opt} + bp * 2 + bm))
		done
	)
	((sty--))
	floatchbpbm
}
floatchbpbm() {
	(
		for opt in ${!chooseopt[@]}; do
			printf '\e[%s;%sH' $sty $stx
			if [ "$opt" = "$selopt" ]; then
				printf "${style[selected]}%*s" $(( ${#opt} + bp * 2 ))
			else
				printf "${style[button]}%*s" $(( ${#opt} + bp * 2 ))
			fi
			stx=$((stx + ${#opt} + bp * 2 + bm))
		done
	)
}
winkey() {
	change=true
	printf '\e[m'
	local -a kbd=()
    if read -rsN1 kbd[0]; then # Check for ready input
		while read -rsN1 -t0.0001 kbd[$i]; do ((i++)); done # Multibyte hack
		case "$focus" in
			window)
				case "$(printf '%s' "${kbd[@]}")" in
					"${windowkey[up]}"*) ((floatpositiony--)) && (( floatpositiony < 1 )) && floatpositiony=1 && change=false ;;
					"${windowkey[down]}"*) ((floatpositiony++)) && (( floatpositiony > LINES - floatsizey )) && floatpositiony=$(( LINES - floatsizey )) && change=false ;;
					"${windowkey[right]}"*) ((floatpositionx++)) && (( floatpositionx > 1 + COLUMNS - floatsizex )) && floatpositionx=$(( 1 + COLUMNS - floatsizex )) && change=false ;;
					"${windowkey[left]}"*) ((floatpositionx--)) && (( floatpositionx < 1 )) && floatpositionx=1 && change=false ;;
					"${windowkey[vsizem]}") ((floatsizey--)) ;;
					"${windowkey[vsizep]}") ((floatsizey++)) ;;
					"${windowkey[hsizem]}") ((floatsizex--)) ;;
					"${windowkey[hsizep]}") ((floatsizex++)) ;;
					'	') true;;
					*) redraw; return 69;;
				esac
				;;
			choose)
				case "$(printf '%s' "${kbd[@]}")" in
					"${windowkey[right]}"*) ((seloptdc++)); (( seloptdc > ( ${#chooseopt[*]} - 1 ) )) && seloptdc=$(( ${#chooseopt[*]} - 1 ));;
					"${windowkey[left]}"*) ((seloptdc--)); ((seloptdc<0)) && seloptdc=0;;
					'')
						eval "${chooseopt[$selopt]}";;
				esac
				selopt="${optdc[seloptdc]}"
				;;
		esac
		case "$(printf '%s' "${kbd[@]}")" in
			'	')
				case "${window[type]}" in
					'choose')
						if [ $focus = window ]; then
							focus=choose
							selopt="${optdc[seloptdc]}"
						else
							focus=window
							selopt=''
						fi
						;;
				esac
				;;
		esac
	fi
}

builtin_syntax_bash() {
	case "${word:0:2}" in
		'"$') printf "${style[quotevar]}%s${rst}" "${word}"; return ;;
	esac
	case "${word:0:1}" in
		'#') printf "${style[comment]}%s${rst}" "${word}" && comment=true; return;;
		'$') printf "${style[variable]}%s${rst}" "${word}"; return ;;
		'-') printf "${style[option]}%s${rst}" "${word}"; return ;;
	esac
	"${comment}" && printf "${style[comment]}%s${rst}" "${word}" && return
	case "${word}" in
		'||') printf "${style[flow]}%s${rst}" "${word}"; return ;;
		'&&') printf "${style[flow]}%s${rst}" "${word}"; return ;;
		']') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		'[') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		'[[') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		']]') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		')') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		'(') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		'{') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		'}') printf "${style[bracket]}%s${rst}" "${word}"; return ;;
		';') printf "${style[flow]}%s${rst}" "${word}"; return ;;
		*"'"*) printf "${style[quote]}%s${rst}" "${word}" && return ;;
		*'"'*) printf "${style[dquote]}%s${rst}" "${word}"&& return ;;
		*'='*) printf "${style[set]}%s${rst}" "${word}"; return ;;
	esac
		   
	[[ "${word: -2}" = '()' ]] && printf "${style[fn]}%s${rst}" "${word}" && return
	case "${word}" in
		'echo'|'return'|'case'|'esac'|'for'|'while'|'do'|'done'|'if'|'elif'|'else'|'printf'|'fi'|'continue'|'exit'|'bind'|'then'|'break'|'read'|'declare'|'typeset'|'local'|'let'|'shopt'|'trap'|'set'|'eval') printf "${style[keyword]}%s${rst}" "${word}" && return
	esac
	printf "${rst}%s" "${word}"
}
builtin_syntax_unknown() {
	printf "${rst}%s" "${word}"
}
builtin_syntax_conf(){
	[[ "${word}" =~ "#" ]] && printf "${style[comment]}%s${rst}" "${word}" && comment=true && return
	"${comment}" && printf "${style[comment]}%s${rst}" "${word}" && return
	printf "${rst}%s" "${word}"
}

syntax() {
	for s in "${!syntax[@]}"; {
		[ "$s" = "$filetype" ] && "${syntax[$s]}" && return
	}
	"${syntax[unknown]}"
}
#colour(){
#	printf "\033[%s;%s;%sm%s\033[0;0m" "$1" "$2" "$3" "$4"
#}
basenam() {
	for file in "$@"; do
	    file="${file%/}"
	    printf '%s\n' "${file##*/}"
	done
}
filetype(){
	[ $# = 0 ] && return
	IFS='.'
	filename="${1%/}"
	filename="${filename##*/}"
	[ "$filename" = 'COMMIT_EDITMSG' ] && echo conf && return
	filenamesplit=($filename)
	extension="${filenamesplit[-1]}"
	[ "${#filenamesplit[@]}" -gt 1 ] && echo "$extension" && return
	mapfile -n 1 file_data < "$1"
	shebang="$(echo -n "${file_data[@]}")"
	[ ! "${shebang:0:1}" = '#' ] && echo unknown && return
	shebang="${shebang%/}"
	IFS=' '
	shebang="${shebang##*/}"
	shebangsplit=($shebang)
	printf '%s\n' "${shebangsplit[-1]}"	
}
set_buffer_file() {
	printf '\e[%s;0H' "${LINES}"
	printf '\e[D\033[1;93;108m' #make prompt nicer
    bind 'set disable-completion off' 2>/dev/null # Enable completion
    printf '\e[?25h' # Enable cursor
    if read -rei "$1$file" -p "${file_prompt}" file; then
        modified=true
    fi
    bind 'set disable-completion on' 2>/dev/null
}
read_buffer() {
	filetype="$(filetype "$1")"
    #set_buffer_file "$1" # Update target file (pass on default if present)
	file="$1"
    mapfile -t -O 1 buffer <"$file" # Read file into an array
    pipesyntax < "$file" | mapfile -t -O 1 buffersyntax  # Read file into an array
    if [[ "${buffer[1]}" ]]; then # Ensure that something was actually read into the file
        line=1 # Indicate that we have a buffer loaded
        modified=false
        message="${file}: ${#buffer[@]}"
    else
        message="{$file}: empty"
    fi
}
pickprep() {
	clr
    printf "${style[windowline]}%s\e[?25l%*s\r" "Open file..." "$(( $COLUMNS - 12 ))"
	printf "${style[windowcontent]}\n"
	for ((i=3;i<=$LINES;i+=1)); do
		printf '%*s\n' "$COLUMNS"
	done
	printf "${style[infoline]}\e[?25l%*s\r" "$COLUMNS"
	printf 'bottom info bar'
	printf "${style[windowcontent]}"
	printf "\033[2;0H"
}
filepick() {
	dc=0
	offsetst=0
	local -i ik=1
	pickprep
	pickdraw
	local -a kb=()
	while true; do
		if read -rsN1 -t"${options[timeout]}" kb[0]; then # Check for ready input
			while read -rsN1 -t0.0001 kb[$ik]; do ((ik++)); done # Multibyte hack
			case "$(printf '%s' "${kb[@]}")" in
				${editkey[up]}*) ((dc--)) ;;
				${editkey[down]}*) ((dc++)) ;;
				'')
					#return to starting dir
					if [ -d "${direc[dc]}" ]; then
						cd "${direc[dc]}"
						offsetst=0
						dc=0
						pickprep
					else
						printf '\e[?1047h' # Switch to alternative buffer
						echo -ne "\e[?1000;1006;1015h" #enable mouse tracking
						read_buffer "${direc[dc]}"
						redraw
						break
					fi
					;;
				*) continue;;
			esac
			(( "$dc" > ( "${#direc[@]}" - 1))) && ((dc--)) && continue
			(( "$dc" < 0 )) && ((dc++)) && continue
			(( "$dc" > ( LINES - 5 + offsetst ) )) && ((offsetst++))
		    (( "$dc" < ( 2 + offsetst ) )) && ((offsetst--))
		fi
		kb=()
		pickdraw
		printf "\033[%s;0H" $LINES
		printf "${style[infoline]}\e[?25l%*s\r" "$COLUMNS"
		printf '%s:%s' "$dc" "${direc[dc]}"
	done
}
pickdraw() {
	printf "\033[1;0H"
	printf "${style[windowline]}%s\e[?25l%*s\r" "Open file..." "$(( $COLUMNS - 12 ))"
	printf "${style[windowcontent]}\n"
	direc=($(pickls))
	offseten=$(( offsetst + ( LINES - 2 ) ))
	for il in "${!direc[@]}"; do
		if [ $il -ge $offsetst ] && [ $il -lt $offseten ]; then
			if [ $dc = $il ]; then
				printf "${style[selected]}\e[?25l%*s\r" "$COLUMNS"
				printf "%s\n" "${direc[il]}"
			else
				if [ -d "${direc[il]}" ]; then
					printf "${style[interactive]}\e[?25l%*s\r" "$COLUMNS"
					printf "%s\n" "${direc[il]}"
				else
					printf "${style[windowcontent]}\e[?25l%*s\r" "$COLUMNS"
					printf "%s\n" "${direc[il]}"
				fi
			fi
		fi
	done
	printf "${style[windowcontent]}\e[?25l%*s\r" "$COLUMNS" #fixes some stuff
}
pickls() {
	printf '..\n'
	printf '%s\n' *
}

write_buffer() {
    true >"$file" # Set the file to an empty text file
    for ln in "${buffer[@]}"; do # Write in the buffer to the file
        echo "$ln" >>"$file"
    done
    modified=false
    message="Wrote ${#buffer[@]} lines to '$file'"
}
megaredraw(){
	printf '%s\n' "${buffer[@]}" | pipesyntax | mapfile -t -O 1 buffersyntax
}
megaredrawline(){
	buffersyntax[line]="$(printf '%s' "${buffer[line]}" | pipesyntax)"
}
tabrender(){
	IFSbck="$IFS"
	IFS=
	while read -rsn1 char
	do
		[ "$char" = " " ] && printf ' ' && continue
		[ "$char" = "	" ] && printf '\033[0;37;48m%s\033[0;0m' "${options[tabchar]}" && continue
		printf '%s' "$char"
	done
	IFS="$IFSbck"
}
tabrenderraw(){
	IFSbck="$IFS"
	IFS=
	while read -rsn1 char
	do
		[ "$char" = " " ] && printf ' ' && continue
		[ "$char" = "	" ] && printf '%s' "${options[tabchar_alt]}" && continue
		printf '%s' "$char"
	done
	IFS="$IFSbck"
}
new_line() {
    buffer=("" "${buffer[@]:1:line}" "" "${buffer[@]:line+1}")
    unset 'buffer[0]'
    modified=true
	megaredraw
	down
	redraw
}

delete_line() {
    buffer=("" "${buffer[@]:1:line-1}" "${buffer[@]:line+1}")
    unset 'buffer[0]'
    ((line > ${#buffer[@]})) && up
    modified=true
    megaredraw
	redraw
}

quit() {
	if [[ "$modified" == "true" ]]; then
		dialogquit
	else
		die
	fi

}
quit_old() {
	printf '\e[%s;0H' "${LINES}"
	printf '\e[D\033[1;93;108m' #make prompt nicer
    if [[ "$modified" == "true" ]]; then
        while :; do
            read -rsN1 -p "Buffer modified, save before close? [Y/n/c]" choice
            case "$choice" in
            Y|y) write_buffer; die;;
            N|n) die;;
            C|c) message="Quit canceled"; break;;
            *) continue;;
            esac
        done
    else
        die
    fi
}

up() {
    for ((i = 0; i < ${1:-1}; i++)); do
        ((line > 1)) && ((line--)) # As long as we can keep going up, go up
        ((line < base)) && ((base--)) # Push back the top if we need to
        ((base <= 0)) && base=1 # Don't push back if our base is at 1
        [ -z "$bckrl" ] && bckrl="${rl}"
        (( "${#buffer[line]}" < "${rl}" )) && rl="${#buffer[line]}"
        (( "${#buffer[line]}" > "${rl}" )) && rl=bckrl
    done
	redraw
}

page_up() {
    up $((LINES - 3))
}

down() {
    for ((i = 0; i < ${1:-1}; i++)); do
        ((line < ${#buffer[@]})) && ((line++)) # If we can go down, go down
        ((line > base + LINES - 3)) && ((base++)) # Move window down if needed
        [ -z "$bckrl" ] && bckrl="${rl}"
        (( "${#buffer[line]}" < "${rl}" )) && rl="${#buffer[line]}"
        (( "${#buffer[line]}" > "${rl}" )) && rl=bckrl
    done
	redraw
}

page_down() {
    down $((LINES - 3))
}

execute() {
    ((line == 0)) && return # If the line is not possible, do nothing
    printf '\e[?25h\e[%sH' "$((line + 2 - base))" # Reset cursor position and enable cursor
    read -re -p "$(printf '%4s ' "$")" # Present editable line
    if [[ "$REPLY" != "${buffer[line]}" ]]; then # If the line is changed, update and inform
        buffer[line]="$($REPLY)"
        modified=true
    fi
    megaredraw
    redraw
}
right() {
	case "${buffer[line]}" in
		*)((rl++));;
	esac
	[ "$rl" -gt "${#buffer[line]}" ] && { rl=0; down; }
	bckrl=
	redraw
}
left() {
	((rl--))
	[ "$rl" -lt 0 ] && { up; rl="${#buffer[line]}"; }
	bckrl=
	redraw
}
shell() {
	printf "\033c"
	bash
	redraw
}

die() {
    bind 'set disable-completion off' 2>/dev/null # Enable completion
    printf '\e[?25h\e[?7h\e[?1047l' # Reset terminal to sane mode
    printf "\e[?1049l" # switch back to main buffer
    echo -e "\e[?1000;1006;1015l" #disable mouse tracking
    exit "${errno:-0}" # Assume that we are exiting without an error
}
mtoggle() {
	[ "${options[mouse]}" = true ] && echo -ne "\e[?1000;1006;1015l" && options[mouse]=false && return
	[ "${options[mouse]}" = false ] && echo -ne "\e[?1000;1006;1015h" && options[mouse]=true && return
}
menuclick() {
	#determine which item should be triggered
	local p=$1
	local cx=0
	for a in "${!menuline[@]}"; {
		la="${#a}"
		((p>cx)) && ((p<(cx + la + 1))) && ${menuline[$a]}
		cx=$(( cx + la + 1 ))
	}
}
menu() {
	local -i dc=0
	printf '\e[?25l'
	while true; do
		local -a k=()
		local -i i=1
		printf '\e[0;0H'
		local mi=0
		for action in "${!menucon[@]}"; do
			if [ $mi = $dc ]; then
				printf "${style[menuitemselected]}%s\e[0;0m\n" "$action"  
			else
				printf "${style[menuitem]}%s\e[0;0m\n" "$action"
			fi
			((mi++))
		done
		local -a kb=()
        if read -rsN1 -t"${options[timeout]}" kb[0]; then # Check for ready input
			while read -rsN1 -t0.0001 kb[$i]; do ((i++)); done # Multibyte hack
			case "$(printf '%s' "${kb[@]}")" in
				${editkey[up]}*) ((dc--)) ;;
				${editkey[down]}*) ((dc++)) ;;
				'')
					mi=0
					for action in "${!menucon[@]}"; do
						[ $mi = $dc ] && ${menucon[$action]}
						printf '%s\n' $mi $dc
						((mi++))
					done
					return
					redraw
					;;
				*) redraw; return ;;
			esac
			(( "$dc" > ( "${#menucon[@]}" - 1))) && ((dc--))
			(( "$dc" < 0 )) && ((dc++))
		fi
	done
}
redraw() {
	if [ "$hasrefresh" = true ]; then
		printf "\e[0m\e[H${style[windowline]}\e[?25l%*s\r" "$COLUMNS"
	else
		printf "\e[0m\e[H${style[menuline]}\e[?25l%*s\r" "$COLUMNS"
	fi
	printf '%s ' "${!menuline[@]}"
	printf '\e[0m'
    for ((i = base; i - base < LINES - reservedlines; i++)); do # Iterate over shown lines
		printf "${style[numberselected]}"
        ((i != line)) && printf "${style[number]}" # Fade line number if not selected
        ((i > ${#buffer[@]})) && printf "\n${style[numberempty]}\e[K   ~\e[m" || \
			if [ "${options[todonote]}" = true ]; then
				case "${buffer[i]}" in
					*"TODO: "*|*TODO:) printf "\n\e[K%4s\e[m ${style[TODO]}%s\033[0;0m" "$i" "$(printf '%s' "${buffer[i]}" | tabrenderraw)";;
					*"NOTE: "*|*NOTE:) printf "\n\e[K%4s\e[m ${style[NOTE]}%s\033[0;0m" "$i" "$(printf '%s' "${buffer[i]}" | tabrenderraw)";;
					*) printf "\n\e[K%4s\e[m %s" "$i" "${buffersyntax[i]}";;
				esac
			else
				printf "\n\e[K%4s\e[m %s" "$i" "${buffersyntax[i]}"
			fi
            #TODO: make proper coloring based on variable for future config
	done
	(printf "\n\e[?25l${style[infoline]}%*s\r %s (%s,%s)\e[m" \
			"$COLUMNS" "$message" \
			"$(basenam "$file") ($filetype)" "$line" "${rl}") # Status line, among others
    printf '\e[?25h\e[%s;%sH' $((line + 2 - base)) $(( rl + 6 )) # move cursor to the line
}
backspace() {
	while [ "${#buffer[line]}" = 0 ]; do
		delete_line
	done
	buffer[line]="${buffer[line]:0:$(( rl - 1 ))}${buffer[line]:${rl}}" #add the key at $rl (cursor position)
	left #go left with cursor
	megaredrawline #not sure why this is needed but it prevents duplication of the letter
	redraw #draw it
	modified=true
}
keytype() {
	hexkey=()
	case "$1" in
		${editkey[pgup]}) page_up; return;;
		${editkey[pgup]}) page_down; return;;
		${editkey[up]}*) up; return;;
		${editkey[down]}*) down; return;;
		${editkey[right]}*) right; return;;
		${editkey[left]}*) left; return;;
	esac
	
	i=0
	echo "$1" | while read -rn1; do
		hexkey[i]="$(printf "%x\n" "'${1:$i}")"
		((i++))
	done
	#clear        #stuff for debugging
	#echo "${hexkey[@]}" #stuff for debugging
	#message="${hexkey[@]}"
	#read -rsn1         #stuff for debugging
	
	for str in "${!stroke[@]}"; do
		[ "$str" = "${hexkey[*]}" ] && "${stroke[$str]}" && return
	done
	#TODO: make mouse scrolling nice instead of ignoring it

	#parse mouse stuff somewhatish weirdly
	[ "${hexkey[0]}" = '1b' ] && {
		a="$1"
		[ "${a: -1}" = 'm' ] && {
			value=0
			echo "$a" | while read -rsn1 mchar; do
				case "$mchar" in
					'0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|9)tmp="${tmp}${mchar}";;
					'm'|'M'|';') {
						[ "$value" = '0' ] && mode="${tmp}" && tmp=
						[ "$value" = '1' ] && x="${tmp}" && tmp=
						[ "$value" = '2' ] && y="${tmp}" && tmp=
					};;
				esac
				case "$mchar" in
					';')((value++));;
					'm'|'M')value=0 && break;;
				esac
			done
		}
		#limitations of movenment
		[ $y = 1 ] && menuclick $x && return #handle menuline
		[ $x -lt 6 ] && {
			if [ "$mode" = 0 ]; then
				line=$(( base + ( y - 2 ) ))
				redraw
			elif [ "$mode" = 2 ]; then #VERY BAD SOLUTION, TODO: FIX
				clr
				echo enter line number
				read -r line
				scrinit
				redraw
			fi
			return
		}
		line=$(( base + ( y - 2 ) ))
		rl=$(( x - 6 ))
		((line > ${#buffer[@]})) && line=${#buffer[@]}
		((rl > ${#buffer[line]})) && rl=${#buffer[line]}
		redraw
		return
	}
	
	buffer[line]="${buffer[line]:0:${rl}}$1${buffer[line]:${rl}}" #add the key at $rl (cursor position)
	#go right with cursor
	megaredrawline #not sure why this is needed but it prevents duplication of the letter
	right
	modified=true
}
main() {
	scrinit
    if [[ "$1" ]]; then # If a file was provided in the terminal pre-load it
        #redraw # Draw out the UI before loading file
        read_buffer "$1"
    else
		filepick # enter the file selector
	fi
    redraw
    while true; do
        local -a k=()
        local -i i=1    
        if read -rsN1 -t${options[refresh_timeout]} k[0]; then # Check for ready input
           while read -rsN1 -t0.0001 k[$i]; do ((i++)); done # Multibyte hack
            keytype "$(printf '%s' "${k[@]}")" # Handle keypress event
        fi
    done
}
pipesyntax() {
	comment=false
	#stringone=false
	#stringtwo=false
	word=
	bckIFS="${IFS}"
	IFS=
	readstuff() {
		while read -rsn1 char
		do
			[ "$char" = " " ] && syntax && word='' && printf ' ' && continue
			[ "$char" = "	" ] && syntax && word='' && printf '\033[0;37;48m%s\033[0;0m' "${BANO_RENDER_TAB:=.}" && continue
			[ -z "$char" ] && syntax && word='' comment='false' && echo && continue
			word="${word}${char}" && printf '%s\e[%sD' "$word" "${#word}"
		done
	}
	readstuff
	IFS="${bckIFS}"
}
main "$@"
printf '\e[?7h'
