#!/bin/bash

hi
bae
NOTE:
++++++++++++++++hi
		TODO: do fucking something nice
																									ae
hello i do echhello i do echo
$pwd
${ls}
"$ae"
"${tf}"
'idk'"ls" "ls" 'tf'
a=n
oe() {
			pwd
}
idk

y 
