#!/bin/bash
wtf() {
	{
		pwd
	}
	return $(( 0 + 1))
}
	ae

NOTE: an	tab	spaces
	TODO: stuff &	stuf
potato
salad
TODO: todo
				bbbbbbbbbb	bbbbbbbbbbbbbb
			bbbbbb	bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
		bbbbbbbbbbbbbbbbbbbbb	bbbbbbbbbb
	bbbbbbbbb	bbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbb	bbbbbbbbbbb
bbbbb	bbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbb	bbbbbbbbbbbbbb

if 
NOTE:


	abcdef
abcdef
