#!/bin/bash
## ebashs
extension bcreen
	version: '0.0.2.1'

## Bcreen -- Tiling interface for Ebashs
# Will be probably merged back into Ebashs once it'll be robust & stable enoughish

# Modifier key
global-set-key "$(kbd C-r)" 'bcreen-prefix'

# Bcreen keybindings
add-mode bcreen
	:: "$(kbd r)" 'bcreen'
	:: "$(kbd v)" 'tile-vertical'
	:: "$(kbd h)" 'tile-horizontal'
	:: "$(kbd k)" 'delete-buffer'

@@ bcreen-prefix
:: Handles Bcreen keybindings
function bcreen-prefix {
	switch-mode bcreen
}

@@ bcreen
:: Bcreen extension "$bcreen_version"
:: Main Bcreen function 
::
:: C-r r redraw tiling
:: C-r v split vertically
:: C-r h split horizontally
:: C-r k delete buffer
function bcreen {
	tile-buffers
}

function tile-buffers {	
	log info "tile redraw-set ${options[tile-mode]}"
	bck_current_buffer="$current_buffer"
	redraw_tiled=1
	case "${options[tile-mode]}" in
		vertical)
			target_x=$(( COLUMNS / ${#buffers_l[@]} ))
			target_x_offset=1
 			target_y_offset=1
			target_y=$((LINES - 1));;
		horizontal)
			target_y=$(( LINES / ${#buffers_l[@]} ))
			target_x_offset=1
 			target_y_offset=1
			target_x=$COLUMNS;;
		single)
			target_y=$LINES
			target_x_offset=1
 			target_y_offset=1
			target_x=$COLUMNS
			redraw_tiled=0;;
	esac
	for b in "${buffers_l[@]}"; do
		set-buffer "$b"
		bf_d[size-x]=$target_x
		bf_d[loc-x]=$target_x_offset
		bf_d[size-y]=$target_y
		bf_d[loc-y]=$target_y_offset
		case "${options[tile-mode]}" in
			vertical)
				target_x_offset=$((target_x_offset + target_x));;
			horizontal)
				target_y_offset=$((target_y_offset + target_y))
		esac
		redraw
	done
	set-buffer "$bck_current_buffer"
}

@@ tile-vertical
:: Tile buffers vertically
function tile-vertical {
	options[tile-mode]='vertical'
	tile-buffers
}

@@ tile-horizontal
:: Tile buffers horizontally
function tile-horizontal {
	options[tile-mode]='horizontal'
	tile-buffers
}

defun tile-single
	:: Makes currently selected buffer fullscreen
	function = {
		options[tile-mode]='single'
		bf_d[size-x]=$COLUMNS
		bf_d[size-y]=$((LINES - 1))
		bf_d[loc-x]=1
		bf_d[loc-y]=1
		redraw_tiled=0
		redraw
	}
nufed
