#!/bin/bash
## ebashs
extension bloat
	version: 0.1.0

## Bloat -- Floating interface for Ebashs

# Modifier key
global-set-key "$(kbd C-r)" 'bloat-prefix'

# Bcreen keybindings
add-mode bloat
	:: "$(kbd h)" 'redraw-windows'

	:: "$(kbd h)" 'window-left'
	:: "$(kbd j)" 'window-down'
	:: "$(kbd k)" 'window-up'
	:: "$(kbd l)" 'window-right'

	:: "$(kbd C-h)" 'window-width+'
	:: "$(kbd C-j)" 'window-height+'
	:: "$(kbd C-k)" 'window-height-'
	:: "$(kbd C-l)" 'window-width-'
	
defun bloat-prefix
	:: Handles Bloat keybindings
	function = {
		switch-mode bloat
	}

defun redraw-windows
	:: Redraw all active buffers
	function = {
		clear-screen
		bck_current_buffer="$current_buffer"
		for b in "${listbuffers[@]}"; do
			set-buffer "$b"
			redraw
		done
		set-buffer "$bck_current_buffer"
	}
	
## Moving
defun window-left
	:: Moves window to left
	function = {
		((bf_d[pos-x]--))
		redraw-windows
	}

defun window-right
	:: Moves window to right
	function = {
		((bf_d[pos-x]++))
		redraw-windows
	}

defun window-down
	:: Moves window down
	function = {
		((bf_d[pos-y]++))
		redraw-windows
	}

defun window-up
	:: Moves window up
	function = {
		((bf_d[pos-y]--))
		redraw-windows
	}

## Resizing
defun window-width+
	:: Increase width of window
	function = {
		((bf_d[size-x]++))
		redraw-windows
	}

defun window-width-
	:: Decrease width of window
	function = {
		((bf_d[size-x]--))
		redraw-windows
	}

defun window-height+
	:: Increase height of window
	function = {
		((bf_d[size-y]++))
		redraw-windows
	}

defun window-height-
	:: Decrase height of window
	function = {
		((bf_d[size-y]--))
		redraw-windows
	}
nufed
