#!/bin/bash
## ebashs

# this is still really proof of concept and is missing lot of stuff,
# contribution is welcome <3
extension evil
	version: wip-2

set-options
	:: default_mode command
	:: command-prompt :
	:: esc-to-meta 0

keys_global=() # clear out default emacsy global mode
global-set # pretty much only arrow keys and pgup & pgdown
	:: '[up]' previous-line
	:: '[down]' next-line
	:: '[right]' forward-char
	:: '[left]' backward-char
	:: '[next]' scroll-down
	:: '[prior]' scroll-up

# default command mode
add-mode command
	:: "$(kbd l)" forward-char
	:: "$(kbd h)" backward-char
	:: "$(kbd j)" next-line
	:: "$(kbd k)" previous-line
	:: "$(kbd i)" set-insert-mode
	:: "$(kbd a)" set-insert-mode-append
	:: "$(kbd A)" set-insert-mode-append-end
	:: "$(kbd :)" execute-extended-command
	:: "$(kbd 0)" move-beginning-of-line
	:: "$(kbd _)" move-beginning-of-line
	:: "$(kbd ^)" move-beginning-of-line
	:: "$(kbd $)" move-end-of-line
	:: "$(kbd d)" delete-line
	:: "$(kbd x)" delete
	mode-options
		:: else :

# bare inserter mode
add-mode insert
	:: 'ESC' set-command-mode
	mode-options
		:: else 'insert'

@@ set-command-mode Switch to command mode.
function set-command-mode {
	printf '\033[0 q'
	bf_d[mode]=command
	redraw-statusline
	redraw-cursor
}
@@ set-insert-mode Switch to insert mode.
function set-insert-mode {
	printf '\033[5 q'
	bf_d[mode]=insert
	redraw-statusline
	redraw-cursor
}
@@ set-insert-mode-append Move forward and switch to insert mode.
function set-insert-mode-append {
	printf '\033[5 q'
	bf_d[mode]=insert
	redraw-statusline
	forward-char
	redraw-cursor
}
@@ set-insert-mode-append-end Move to end of line and switch to insert mode.
function set-insert-mode-append-end {
	printf '\033[5 q'
	bf_d[mode]=insert
	move-end-of-line
}

set-alias
	:: 'q!' 'die'
	:: 'q' 'quit'
	:: 'w' 'write-buffer'
