#!/bin/bash
options+=(
	[default_mode]='command'
	[cmd_prompt]=':'
)
declare -A keys_command
keys_command=(
	[${keys_def[previous_line]}]='previous-line'
	[${keys_def[next_line]}]='next-line'
	[${keys_def[forward_char]}]='forward-char'
	[${keys_def[backward_char]}]='backward-char'
	[${keys_def[scroll_down]}]='scroll-down'
	[${keys_def[scroll_up]}]='scroll-up'
	[68 0]='backward-char'
	[6a 0]='next-line'
	[6b 0]='previous-line'
	[6c 0]='forward-char'
	[69 0]='insertmode'
	[61 0]='ansertmode'
	[3a 0]='execute-extended-command'
)
keys_edit=(
	[${keys_def[previous_line]}]='previous-line'
	[${keys_def[next_line]}]='next-line'
	[${keys_def[forward_char]}]='forward-char'
	[${keys_def[backward_char]}]='backward-char'
	[${keys_def[scroll_down]}]='scroll-down'
	[${keys_def[scroll_up]}]='scroll-up'
	[7f 0]='backspace'
	[1b 0]='commandmode'
)
commands=(
	[q]='quit'
	[q!]='die'
	[newline]='newline'
	[set-buffer-file]='find-file'
	[read-file]='read-buffer'
	[w]='write-buffer'
	[delete-line]='delete_line'
	[toggle-mouse]='toggle-mouse'
	[execute]='execute'
	[shell]='shell'
	[about]='about'
	[backspace]='backspace'
	[menu]='menu'
	[menul]='menulinemenu'
	[input]='inputcodes'
	[scroll-up]='scroll-up'
	[scroll-down]='scroll-down'
	[dired]='dired'
)

commandmode() { mode="command"; redraw; }
insertmode() { mode="edit"; redraw; }
ansertmode() {
	forward-char
	mode="edit"; redraw;
}
