#!/bin/bash
## ebashs

# this is still really proof of concept and is missing lot of stuff,
# contribution is welcome <3
extension evil
	version: wip-2.1

set-options
	:: default_mode command
	:: command-prompt :
	:: esc-to-meta 0
	:: keep-message 1
	:: menu-line 0
	:: tabchar '        '
	:: line-number-mode 0
	:: empty-line-char ''

keys_global=() # clear out default emacsy global mode
global-set # pretty much only arrow keys and pgup & pgdown
	:: '[up]' previous-line
	:: '[down]' next-line
	:: '[right]' forward-char
	:: '[left]' backward-char
	:: '[next]' scroll-down
	:: '[prior]' scroll-up

# default command mode
add-mode command
	:: "$(kbd l)" forward-char
	:: "$(kbd h)" backward-char
	:: "$(kbd j)" next-line
	:: "$(kbd k)" previous-line
	:: "$(kbd i)" set-insert-mode
	:: "$(kbd I)" set-insert-mode-beginning
	:: "$(kbd a)" set-insert-mode-append
	:: "$(kbd A)" set-insert-mode-append-end
	:: "$(kbd :)" execute-extended-command
	:: "$(kbd 0)" move-beginning-of-line
	:: "$(kbd _)" move-beginning-of-line
	:: "$(kbd ^)" move-beginning-of-line
	:: "$(kbd $)" move-end-of-line
	:: "$(kbd d)" delete-line
	:: "$(kbd x)" delete
	:: "$(kbd v)" set-mark-command
	mode-options
		:: else :

# bare inserter mode
add-mode insert
	:: 'ESC' set-command-mode
	mode-options
		:: else 'insert'

@@ set-command-mode Switch to command mode.
function set-command-mode {
	printf '\033[0 q'
	bf_d[mode]=command
	redraw-statusline
	message=''
	redraw-commandline
	redraw-cursor
}
@@ set-insert-mode Switch to insert mode.
function set-insert-mode {
	printf '\033[5 q'
	bf_d[mode]=insert
	redraw-statusline
	message='-- INSERT --'
	redraw-commandline
	redraw-cursor
}
@@ set-insert-mode-append Move forward and switch to insert mode.
function set-insert-mode-append {
	printf '\033[5 q'
	bf_d[mode]=insert
	redraw-statusline
	message='-- INSERT --'
	redraw-commandline
	forward-char
	redraw-cursor
}
@@ set-insert-mode-append-end Move to end of line and switch to insert mode.
function set-insert-mode-append-end {
	printf '\033[5 q'
	bf_d[mode]=insert
	message='-- INSERT --'
	move-end-of-line
}
@@ set-insert-mode-beginning Move to start of line and switch to insert mode.
function set-insert-mode-beginning {
	printf '\033[5 q'
	bf_d[mode]=insert
	message='-- INSERT --'
	move-beginning-of-line
}

set-alias
	:: 'q!' 'die'
	:: 'q' 'quit'
	:: 'w' 'write-buffer'

function redraw-statusline {
	printf '\e[?25l'
	((options[mode-line])) &&
		printf "\e[%s;%sH%b%*s\e[%sG%b%s\e[m" \
			   $((bf_d[size-y] - 1 + bf_d[loc-y]))\
			   "${bf_d[loc-x]}"\
			   "${faces[mode-line]}"\
			   "${bf_d[size-x]}"\
			   "${bf_d[line]},${bf_d[column]}    $((100 * bf_d[line] / bf_d[length]))%"\
			   "${bf_d[loc-x]}"\
			   "${faces[file-name]}"\
			   "${bf_d[file]}"
}
